### ISSUE TITLE
policiesAPI: Add 'employer' Field to InsuredPerson Schema 

### ISSUE THREAD

**Issue by micmuell** [swissfintechinnovations/ca-pension#14]
### Description
Upon reviewing the API specification for the `InsuredPerson` schema, I've identified a enhancement opportunity: the inclusion of an `employer` field. Currently, there is no provision to capture the employment details of the insured person.

### Suggested Change
I propose the addition of an `employer` object to the `InsuredPerson` schema. In this object, only the `name` of the employer would be a required field. The schema could be structured as follows:

employer:
  type: object
  description: Details of the insured person's employer
  required:
    - name
  properties:
    employerId:
      type: string
      description: Swiss Enterprise Identification Number UID
    name:
      type: string
      description: The name of the employer
    address:
      $ref: '#/components/schemas/Address'
      description: The address of the employer
    industry:
      type: string
      description: The industry or sector the employer operates in

### Further considerations
The employer field is optional at the InsuredPerson level, as not all insured persons may have a current employer

**Comment by msacrea** [comment]
Proposed change see https://github.com/swissfintechinnovations/ca-pension/commit/6c7f425613cdefe4c89136e983d42fd10d6ae5da

**Comment by msacrea** [comment]
Resolved with version 1.0.0 of the Pension API.
