### ISSUE TITLE
policiesAPI: Add 'maxPurchaseAmount' Field to the Policy Schema #14

### ISSUE THREAD

**Issue by micmuell** [swissfintechinnovations/ca-pension#16]
**Description**
Upon reviewing the API specification for the Policy schema, I've identified a enhancement opportunity: the inclusion of a maxPurchaseAmount field. 
Currently the maxPurchaseAmount for voluntary purchases is not available on the policies level but only on the "purchasesAPI".

**Suggested Change**
I propose the addition of the maxPurchaseAmount field to the Policy schema:

maxPurchaseAmount:
      type: number
      description: |
        The maximum amount the insured person is permitted to voluntarily contribute to their pension plan.

**Comment by msacrea** [comment]
Proposed change see https://github.com/swissfintechinnovations/ca-pension/commit/44f2981cc7d2b7ee691061bb4a6db101a427c98c

**Comment by msacrea** [comment]
Resolved with version 1.0.0 of the Pension API.
