### ISSUE TITLE
policiesAPI: Add 'homeOwnershipWithdrawal' Field to the vestedBenefits Schema

### ISSUE THREAD

**Issue by micmuell** [swissfintechinnovations/ca-pension#17]
**Description**
Upon reviewing the API specification for the Policy schema, I've identified a enhancement opportunity: the inclusion of a homeOwnershipWithdrawal field.
Currently the homeOwnershipWithdrawal amount is not available.

**Suggested Change**
I propose the addition of the homeOwnershipWithdrawal field to the vestedBenefits schema:

homeOwnershipWithdrawal:
      type: number
      description: 
        The total amount available for the insured person to withdraw or borrow against from their retirement capital for the purpose of financing home ownership.

**Comment by msacrea** [comment]
Proposed change see https://github.com/swissfintechinnovations/ca-pension/commit/ccb60c858a01f0b38d1983ea7ec62ff35cc58877 -> Note: I have proposed a different name for the field.

**Comment by msacrea** [comment]
Resolved with version 1.0.0 of the Pension API.
