### ISSUE TITLE
policiesAPI: Add 'pensionProvider' Field to the Policy Schema

### ISSUE THREAD

**Issue by micmuell** [swissfintechinnovations/ca-pension#18]
Description
Upon reviewing the API specification for the Policy schema, I've identified a enhancement opportunity: the inclusion of a pensionProvider field.
Currently the name of the pension provider (foundation) is not available.

Suggested Change
I propose the addition of the pensionProvider field to the policy schema:

Policy:
      type: object
      description: Details of policy
      required:
        - policyId
        - personId
        - policyNo
        - entryDate
        - salaryData
        - retirementCapital
        - riskBenefits
        - financing
        - pensionProvider  --> NEW FIELD

      properties:
pensionProvider:  --> NEW property
          type: object
          required:
            - providerName
          properties:
providerId:
type: string
description: Swiss Enterprise Identification Number UID            
providerName:
              type: string
              description: The name of the pension provider (foundation).
            providerAddress:
              $ref: '#/components/schemas/Address'
              description: Postal address of the pension provider.

**Comment by msacrea** [comment]
Proposed change see https://github.com/swissfintechinnovations/ca-pension/commit/54759c1ffef83656180cc1d10f14245769c66d5d

**Comment by msacrea** [comment]
Resolved with version 1.0.0 of the Pension API.
