### ISSUE TITLE
policiesAPI: Split lumpSumDeathBenefit into Two Distinct Fields in RiskBenefits schema

### ISSUE THREAD

**Issue by micmuell** [swissfintechinnovations/ca-pension#20]
Objective:
The current insurance schema includes a lumpSumDeathBenefit field that represents a one-off payment in the case of death. We aim to provide more detailed information on lump sum payments by splitting this field into two separate fields: lumpSumWithoutPensionBenefits and lumpSumWithPensionBenefits. This change will allow us to distinguish between lump sum payments made with and without concurrent pension benefits.

Suggested change
Remove the existing lumpSumDeathBenefit field from the RiskBenefits schema.
Add two new fields to the schema:

 schemas:
    RiskBenefits:
      type: object
      description: Benefits in case of death or disability to work
      required:
        - pensionDisabilityFromIllness
        - childPensionDisabilityFromIllness
        - partnerPensionDeathFromIllness
        - orphanPensionDeathFromIllness
        - lumpSumWithoutPensionBenefits  --> NEW
        - lumpSumWithPensionBenefits     --> NEW

lumpSumWithoutPensionBenefits:
          type: number
          format: double
          description: One-off payment in case of death where no other benefits are paid out

lumpSumWithPensionBenefits:
          type: number
          format: double
          description: One-off payment in case of death where other benefits are paid out

**Comment by msacrea** [comment]
Proposed change see https://github.com/swissfintechinnovations/ca-pension/commit/571333f0ed4aa64c56741dc7b97db2a98a991e14
